alias sp='export all_proxy=socks5h://10.10.10.10:20000'
alias unsp='unset all_proxy'
alias cl='clear'
alias gl='glances'
alias nsync='hup_save_to_home rsync'
alias sz='source ~/.zshrc'
alias mv='mv -iuv'
alias yt='download_youtube'
alias ytf='download_youtube_homepage'
alias wt='watch tail -n 20'
